esphome:
  name: mailbox
  friendly_name: Mailbox Lock

esp32:
  board: esp32-c6-devkitm-1
  variant: ESP32C6
  framework: 
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

#This is to make sure adc compiles or else it will throw an error
external_components:
  - source:
      # https://github.com/lboue/esphome/blob/adc_oneshot/esphome/components/adc
      type: git
      url: https://github.com/lboue/esphome
      ref: adc_oneshot
    components: [ adc ]

# Enable deep sleep
deep_sleep:
  id: deep_sleep_1
  wakeup_pin: GPIO2
  wakeup_pin_mode: INVERT_WAKEUP
  run_duration: 30s
  sleep_duration: 6h
    

# UART configuration for fingerprint sensor
uart:
  - id: uart_2
    tx_pin: GPIO5
    rx_pin: GPIO4
    baud_rate: 57600

# Global variables
globals:
  - id: learning_mode
    type: bool
    initial_value: 'false'
  - id: enrollment_in_progress
    type: bool
    initial_value: 'false'
  - id: next_fingerprint_slot
    type: int
    initial_value: '6'

# Relay configuration
switch:
  - platform: gpio
    id: relay
    pin: GPIO3
    name: "Lock Relay"
    restore_mode: ALWAYS_OFF
    on_turn_on: 
      then:
        - deep_sleep.prevent: deep_sleep_1
        - delay: 1.5s
        - switch.turn_off: relay
        - deep_sleep.allow: deep_sleep_1
  - platform: gpio
    id: fingerprint_power
    pin: 
      number: GPIO6
      mode: 
        output: true
        pulldown: true
    inverted: False
    restore_mode: ALWAYS_OFF        
  - platform: restart
    id: restart_button
    name: Reboot

sensor:
  - platform: adc
    pin: GPIO0
    id: battery_voltage
    name: "Battery voltage"
    filters:
     - multiply: 2  # 2×1MΩ voltage divider
  - platform: template
    name: "Wakeup Cause"
    accuracy_decimals: 0
    lambda: return esp_sleep_get_wakeup_cause();

# Boot button configuration
binary_sensor:
  - platform: gpio
    id: boot_button
    pin:
      number: GPIO9
      inverted: true  
    on_press:         
      - deep_sleep.prevent: deep_sleep_1
      - globals.set:
          id: enrollment_in_progress
          value: 'true'
      - lambda: |-
          ESP_LOGI("main", "Enrollment started. Target slot: %d", id(next_fingerprint_slot));
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return id(next_fingerprint_slot);'
          num_scans: 2
      - fingerprint_grow.aura_led_control:
          id: fingerprint_sensor
          state: BREATHING
          color: BLUE
          speed: 200
          count: 0

# Fingerprint sensor configuration
fingerprint_grow:
  id: fingerprint_sensor
  uart_id: uart_2
  on_finger_scan_matched:
    - if:
        condition:
          lambda: 'return !id(enrollment_in_progress);'
        then:
          - lambda: |-
              ESP_LOGI("fingerprint", "Finger matched. ID: %d, Confidence: %d", finger_id, confidence);
          - fingerprint_grow.aura_led_control:
              id: fingerprint_sensor
              state: BREATHING
              speed: 200
              color: BLUE
              count: 1
          - switch.turn_on: relay
  on_finger_scan_invalid:
    - if:
        condition:
          lambda: 'return !id(enrollment_in_progress);'
        then:
          - lambda: |-
              ESP_LOGW("fingerprint", "Unmatched finger scan detected.");
          - fingerprint_grow.aura_led_control:
              id: fingerprint_sensor
              state: FLASHING
              speed: 50
              color: RED
              count: 2
          - deep_sleep.allow: deep_sleep_1
  on_finger_scan_unmatched:
    - if:
        condition:
          lambda: 'return !id(enrollment_in_progress);'
        then:
          - lambda: |-
              ESP_LOGW("fingerprint", "Invalid finger scan detected (e.g., poor placement).");
          - fingerprint_grow.aura_led_control:
              id: fingerprint_sensor
              state: FLASHING
              speed: 25
              color: RED
              count: 2
          - deep_sleep.allow: deep_sleep_1
  on_finger_scan_start:
    - lambda: |-
        if (id(enrollment_in_progress)) {
          ESP_LOGD("fingerprint", "Scan started (Enrollment in progress)");
        } else {
          ESP_LOGD("fingerprint", "Scan started (Normal operation)");
        }
    - if:
        condition:
          lambda: 'return id(enrollment_in_progress);'
        then:
          - fingerprint_grow.aura_led_control:
              id: fingerprint_sensor
              state: BREATHING
              color: BLUE
              speed: 200
              count: 0
  on_enrollment_scan:
    - lambda: |-
        ESP_LOGD("fingerprint", "Enrollment scan: %d for finger_id: %d", scan_num, finger_id);
    - if:
        condition:
          lambda: 'return scan_num == 1;' # After 1st scan of 2
        then:
          - fingerprint_grow.aura_led_control:
              id: fingerprint_sensor
              state: FLASHING
              color: BLUE
              speed: 50
              count: 3
  on_enrollment_done:
    - lambda: |-
        ESP_LOGI("fingerprint", "Enrollment successful for finger_id: %d", finger_id);
    - fingerprint_grow.aura_led_control:
        id: fingerprint_sensor
        state: ALWAYS_ON
        color: BLUE
        speed: 0
        count: 0
    - delay: 1s
    - fingerprint_grow.aura_led_control:
        id: fingerprint_sensor
        state: ALWAYS_OFF
        color: BLUE
        speed: 0
        count: 0
    - globals.set:
        id: next_fingerprint_slot
        value: !lambda 'return id(next_fingerprint_slot) + 1;'
    - globals.set:
        id: enrollment_in_progress
        value: 'false'
    - deep_sleep.allow: deep_sleep_1
  on_enrollment_failed:
    - lambda: |-
        ESP_LOGW("fingerprint", "Enrollment failed for finger_id: %d", finger_id);
    - fingerprint_grow.aura_led_control:
        id: fingerprint_sensor
        state: FLASHING
        color: RED
        speed: 50
        count: 5
    - delay: 1s
    - fingerprint_grow.aura_led_control:
        id: fingerprint_sensor
        state: ALWAYS_OFF
        color: RED
        speed: 0
        count: 0
    - globals.set:
        id: enrollment_in_progress
        value: 'false'
    - deep_sleep.allow: deep_sleep_1

# Enable logging
logger:
  level: DEBUG 

api:
  encryption:
    key: !secret mailbox_encryption_key

ota:
  - platform: esphome
    password: !secret mailbox_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH

  ap:
    ssid: "Mailbox Fallback Hotspot"
    password: !secret mailbox_ap_password
